services:
  apache:
    image: httpd:latest
    container_name: apache_server
    ports:
      - "8081:80"
    volumes:
      - ./html:/usr/local/apache2/htdocs
      - ./config/apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "8082:80"
    volumes:
      - ./html:/usr/share/nginx/html
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: always

  litespeed:
    image: litespeedtech/openlitespeed:latest
    container_name: litespeed_server
    ports:
      - "8083:8088"
    volumes:
      # copy local html to default litespeed index
      - ./html:/usr/local/lsws/Example/html
      - ./config/litespeed/.htaccess:/usr/local/lsws/Example/html/.htaccess
    restart: always
